services:
  front:
    image: mathiasvandaele/project-distributed-calculus-frontend:latest
    container_name: distributed-calculus-front
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.dc-front.rule=Host(`distributed-computing.mathias-vandaele.dev`)"
      - "traefik.http.routers.dc-front.entrypoints=websecure"
      - "traefik.http.routers.dc-front.tls.certresolver=myresolver"
      - "traefik.http.services.dc-front.loadbalancer.server.port=8181"

  back:
    image: mathiasvandaele/project-distributed-calculus-backend:latest
    container_name: distributed-calculus-back
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"

      - "traefik.http.routers.dc-httpserv.rule=Host(`distributed-computing.mathias-vandaele.dev`) && Path(`/last-prime`)"
      - "traefik.http.routers.dc-httpserv.service=dc-httpserv"
      - "traefik.http.routers.dc-httpserv.entrypoints=websecure"
      - "traefik.http.routers.dc-httpserv.tls.certresolver=myresolver"
      - "traefik.http.services.dc-httpserv.loadbalancer.server.port=3030"

      - "traefik.http.routers.dc-socket.rule=Host(`distributed-computing.mathias-vandaele.dev`) && Path(`/ws`)"
      - "traefik.http.routers.dc-socket.service=dc-socket"
      - "traefik.http.routers.dc-socket.entrypoints=websecure"
      - "traefik.http.routers.dc-socket.tls.certresolver=myresolver"
      - "traefik.http.services.dc-socket.loadbalancer.server.port=7878"

networks:
  traefik-public:
    external: true
